In [174]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [175]:
%cd /content/drive/MyDrive/work/NCKU/10902/dl/HW01/images/train/

/content/drive/MyDrive/work/NCKU/10902/dl/HW01/images/train


setp1. 讀取圖片, 擷取圖片特徵, 然後將特徵像素數值, 儲存成0 ~ 255個種類

In [176]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os

In [ ]:
#img = cv2.imread('0_bear.JPEG')

xfiles = os.listdir("./")
xfiles_len = len(xfiles)

train_sample = xfiles_len
train_label  = xfiles_len
# 256 * 3 = 768
pixel_num    = 768

x_train = np.empty((train_sample, pixel_num))
y_train = np.empty(train_label)

print("show len xfiles: ", xfiles_len)

xfile_idx = 0
for xfile_name in xfiles:
    ext = xfile_name.split('_')
    #print("file_name and ext info: ", file_name, ext)
        
    if ext[-1] == "bear.JPEG":
        y_train[xfile_idx] = 0
    else:
        y_train[xfile_idx] = 1
    xfile_idx += 1


# for loop via number of pic
for dataset_num in range(xfiles_len):
  print("show pic name: ", xfiles[dataset_num])
  img = cv2.imread(xfiles[dataset_num])
  rgb_pixel = []
  # 畫出 RGB 三種顏色的分佈圖
  color = ('b','g','r')
  for i, col in enumerate(color):
    histr = cv2.calcHist([img],[i],None,[256],[0, 256])
    #plt.plot(histr, color = col)
    plt.hist(histr.ravel(), 256, [0, 256])
    plt.xlim([0, 256])
    
    # 顯示b, r, g的1維數值
    #print("-- ", col, " --")
    #print(histr.ravel())
    rgb_pixel.extend(histr.ravel())
  x_train[dataset_num:dataset_num + 1] = rgb_pixel[:]
plt.show()


show len xfiles:  2200
show pic name:  290_bear.JPEG
show pic name:  508_bear.JPEG
show pic name:  519_bear.JPEG
show pic name:  961_bear.JPEG
show pic name:  958_bear.JPEG
show pic name:  497_bear.JPEG
show pic name:  179_bear.JPEG
show pic name:  724_bear.JPEG
show pic name:  111_bear.JPEG
show pic name:  411_bear.JPEG
show pic name:  890_bear.JPEG
show pic name:  729_bear.JPEG
show pic name:  706_bear.JPEG
show pic name:  696_bear.JPEG
show pic name:  390_bear.JPEG
show pic name:  796_bear.JPEG
show pic name:  803_bear.JPEG
show pic name:  665_bear.JPEG
show pic name:  428_bear.JPEG
show pic name:  1000_bear.JPEG
show pic name:  646_bear.JPEG
show pic name:  516_bear.JPEG
show pic name:  727_bear.JPEG
show pic name:  987_bear.JPEG
show pic name:  3_bear.JPEG
show pic name:  901_bear.JPEG
show pic name:  361_bear.JPEG
show pic name:  873_bear.JPEG
show pic name:  679_bear.JPEG
show pic name:  248_bear.JPEG
show pic name:  964_bear.JPEG
show pic name:  398_bear.JPEG
show pic name:  21

In [ ]:
rgb_pixel

In [223]:
len(rgb_pixel)

768

In [229]:
x_train

array([[2.86200000e+003, 1.18100000e+003, 1.07400000e+003, ...,
        9.80000000e+001, 7.00000000e+001, 1.02000000e+002],
       [9.01000000e+002, 1.78000000e+002, 2.43000000e+002, ...,
        2.69200000e+003, 3.02700000e+003, 1.34410000e+004],
       [7.27373854e+175, 1.04988942e-153, 4.06007127e+228, ...,
        5.44909707e-096, 3.67904408e+180, 6.06315637e+078],
       ...,
       [1.04988942e-153, 4.06007133e+228, 7.87724961e+025, ...,
        5.44909707e-096, 3.67904610e+180, 6.06315637e+078],
       [2.41726873e-052, 9.30278686e+242, 5.44909707e-096, ...,
        1.04988942e-153, 1.50321821e+161, 5.44909707e-096],
       [2.38232245e+180, 1.80236286e-119, 7.18493834e+165, ...,
        1.04988942e-153, 1.50321822e+161, 5.44909707e-096]])

In [230]:
x_train.shape

(2200, 768)

In [221]:
y_train

array([0., 0., 0., ..., 1., 1., 1.])

In [127]:
x_train = np.empty((1, 4))
x_train[0:1] = [5.1, 3.5, 1.4, 0.2]
y_train = np.empty(1)
y_train[0] = 0

step2. 訓練資料

In [164]:
# sigmoid(x) function
def sigmoid(x):
  #print("show sigmoid x value: ", x)
  #print("show sigmoid value: ", 1/(1 + np.exp(-x)))
  return 1/(1 + np.exp(-x))

# activation function
def activation(x, w, b):
  #print("show np.dot: ", np.dot(x, w))
  return sigmoid(np.dot(x, w) + b)

# updata weight and bias value
def update(x, y, w, b, eta):
  y_pred = activation(x, w, b)
  #print("show y_pred: ", y_pred)
  a = (y_pred - y_train) * y_pred * (1 - y_pred)
  for i in range(pixel_num):
  #for i in range(4):
    w[i] -= eta * 1/float(len(y)) * np.sum(a * x[:, i])
    b    -= eta * 1/float(len(y)) * np.sum(a)
    #print("show a*x[0:1, i]: ", a*x[0:1, i])
    return w, b

In [166]:
# initial weight value
weights = np.ones(pixel_num) / 10
bias = np.ones(1) / 10
for _ in range(15):
  weights, bias = update(x_train, y_train, weights, bias, eta = 0.1)
  #print("weight = %f, bias = %f" % (weights, bias))
  print("weights = ", weights, "bias = ", bias)

show np.dot:  [28108.8]
show sigmoid x value:  [28108.9]
show sigmoid value:  [1.]
show y_pred:  [1.]
show a*x[0:1, i]:  [0.]
weights =  [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1
 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1
 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1
 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1
 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1
 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1
 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1
 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1
 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1
 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1
 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1
 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1

In [168]:
len(weights)

768

In [204]:
x_train

array([[2022.,  544.,  790., ...,  160.,  138.,  734.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.],
       ...,
       [   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.]])

In [169]:
x_train.shape

(1, 768)

In [203]:
y_train

array([1., 1., 1., ..., 1., 1., 1.])

In [172]:
y_train.shape

(1,)

In [216]:
for i in range(len(xfiles)):
  print(xfiles[i], y_train[i])

290_bear.JPEG 0.0
508_bear.JPEG 0.0
519_bear.JPEG 0.0
961_bear.JPEG 0.0
958_bear.JPEG 0.0
497_bear.JPEG 0.0
179_bear.JPEG 0.0
724_bear.JPEG 0.0
111_bear.JPEG 0.0
411_bear.JPEG 0.0
890_bear.JPEG 0.0
729_bear.JPEG 0.0
706_bear.JPEG 0.0
696_bear.JPEG 0.0
390_bear.JPEG 0.0
796_bear.JPEG 0.0
803_bear.JPEG 0.0
665_bear.JPEG 0.0
428_bear.JPEG 0.0
1000_bear.JPEG 0.0
646_bear.JPEG 0.0
516_bear.JPEG 0.0
727_bear.JPEG 0.0
987_bear.JPEG 0.0
3_bear.JPEG 0.0
901_bear.JPEG 0.0
361_bear.JPEG 0.0
873_bear.JPEG 0.0
679_bear.JPEG 0.0
248_bear.JPEG 0.0
964_bear.JPEG 0.0
398_bear.JPEG 0.0
21_bear.JPEG 0.0
124_bear.JPEG 0.0
657_bear.JPEG 0.0
400_bear.JPEG 0.0
544_bear.JPEG 0.0
409_bear.JPEG 0.0
66_bear.JPEG 0.0
1019_bear.JPEG 0.0
748_bear.JPEG 0.0
364_bear.JPEG 0.0
1030_bear.JPEG 0.0
501_bear.JPEG 0.0
464_bear.JPEG 0.0
334_bear.JPEG 0.0
731_bear.JPEG 0.0
321_bear.JPEG 0.0
545_bear.JPEG 0.0
1098_bear.JPEG 0.0
821_bear.JPEG 0.0
109_bear.JPEG 0.0
348_bear.JPEG 0.0
1051_bear.JPEG 0.0
430_bear.JPEG 0.0
346_bear.

In [ ]:
print("-------------------------------------------- test -------------------------------------------------------")

-------------------------------------------- test -------------------------------------------------------


In [ ]:
xx_train = np.empty((5, 3))
xx_train.shape

(5, 3)

In [ ]:
a = [11, 22, 33]

In [ ]:
b = np.array(a)

In [ ]:
b

array([11, 22, 33])

In [ ]:
type(a)

list

In [ ]:
type(b)

numpy.ndarray

In [ ]:
xx_train

In [ ]:
xx_train[0, 0:3] = a

In [ ]:
xx_train[1:2] = a

In [ ]:
xx_train[2:3] = a[:]

In [ ]:
xx_train[3:4] = a[:]

In [ ]:
xx_train[4:5] = b[:]

In [ ]:
xx_train

array([[11., 22., 33.],
       [11., 22., 33.],
       [11., 22., 33.],
       [11., 22., 33.],
       [11., 22., 33.]])

In [ ]:
b

array([1., 2., 3.])

In [48]:
aa = np.empty(400)
for i in range(400):
  if i % 2 == 0:
    aa[i] = 0
  else:
    aa[i] = 1

In [49]:
aa.shape

(400,)

In [50]:
aa

array([0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1.

In [40]:
aa[0] = 10

In [58]:
for i in range(3):
  print(i)

print("----------------------------------------------------------------------------")
for i in range(5):
  print(i)

0
1
2
----------------------------------------------------------------------------
0
1
2
3
4


In [98]:
for _ in range(3):
  print("---")

---
---
---


In [173]:
def sigmoid(x):
  print("show sigmoid x value: ", x)
  print("show sigmoid value: ", 1/(1 + np.exp(-x)))
  return 1/(1 + np.exp(-x))

sigmoid(1.05)*sigmoid(1.05)*(1-sigmoid(1.05))*4.9

show sigmoid x value:  1.05
show sigmoid value:  0.740774899182154
show sigmoid x value:  1.05
show sigmoid value:  0.740774899182154
show sigmoid x value:  1.05
show sigmoid value:  0.740774899182154


0.6970206555422862

In [194]:
bb = "1000_leopard.JPEG"
cc = (bb.split("_"))

#if cc[1] == "bear.JPEG":
if cc[1] == "bear.JPEG":
  dd = 11
else:
  dd = 22

print(dd)

22
