In [27]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [28]:
%cd /content/drive/MyDrive/work/NCKU/10902/dl/HW01/images/train/

/content/drive/MyDrive/work/NCKU/10902/dl/HW01/images/train


setp1. 讀取圖片, 擷取圖片特徵, 然後將特徵像素數值, 儲存成0 ~ 255個種類

In [29]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os

In [30]:
#img = cv2.imread('0_bear.JPEG')

xfiles = os.listdir("./")
xfiles_len = len(xfiles)

train_sample = xfiles_len
train_label  = xfiles_len
# 256 * 3 = 768
pixel_num    = 768

x_train = np.empty((xfiles_len, pixel_num))
y_train = np.empty(xfiles_len)

print("show len xfiles: ", xfiles_len)

xfile_idx = 0
for xfile_name in xfiles:
    ext = xfile_name.split('_')
    #print("file_name and ext info: ", file_name, ext)
    if xfile_idx >= xfiles_len:
      break
    if ext[-1] == "bear.JPEG":
        y_train[xfile_idx] = 0
    else:
        y_train[xfile_idx] = 1
    xfile_idx += 1


# for loop via number of pic
for dataset_num in range(xfiles_len):
#for dataset_num in range(1):
  print("show pic name: ", xfiles[dataset_num])
  img = cv2.imread(xfiles[dataset_num])
  #img = cv2.imread("111_leopard.JPEG")
  
  rgb_pixel = []
  # 畫出 RGB 三種顏色的分佈圖
  color = ('b','g','r')
  for i, col in enumerate(color):
    histr = cv2.calcHist([img],[i],None,[256],[0, 256])
    #plt.plot(histr, color = col)
    #plt.hist(histr.ravel(), 256, [0, 256])
    #plt.xlim([0, 256])
    
    # 顯示b, r, g的1維數值
    #print("-- ", col, " --")
    #print(histr.ravel())
    rgb_pixel.extend(histr.ravel())
  x_train[dataset_num:dataset_num + 1] = rgb_pixel[:] / max(rgb_pixel[:])
#plt.show()


show len xfiles:  1784
show pic name:  278_leopard.JPEG
show pic name:  405_leopard.JPEG
show pic name:  440_leopard.JPEG
show pic name:  539_leopard.JPEG
show pic name:  750_leopard.JPEG
show pic name:  422_leopard.JPEG
show pic name:  817_leopard.JPEG
show pic name:  696_leopard.JPEG
show pic name:  319_leopard.JPEG
show pic name:  723_leopard.JPEG
show pic name:  389_leopard.JPEG
show pic name:  210_leopard.JPEG
show pic name:  838_leopard.JPEG
show pic name:  55_leopard.JPEG
show pic name:  65_leopard.JPEG
show pic name:  738_leopard.JPEG
show pic name:  118_leopard.JPEG
show pic name:  175_leopard.JPEG
show pic name:  149_leopard.JPEG
show pic name:  561_leopard.JPEG
show pic name:  671_leopard.JPEG
show pic name:  607_leopard.JPEG
show pic name:  151_leopard.JPEG
show pic name:  376_leopard.JPEG
show pic name:  879_leopard.JPEG
show pic name:  125_leopard.JPEG
show pic name:  163_leopard.JPEG
show pic name:  271_leopard.JPEG
show pic name:  261_leopard.JPEG
show pic name:  218_le

In [31]:
x_train

array([[0.38701805, 0.06539775, 0.08003905, ..., 0.00585652, 0.00390434,
        0.02830649],
       [0.19150989, 0.02098408, 0.01760733, ..., 0.0065123 , 0.00578871,
        0.03497347],
       [1.        , 0.12890923, 0.13424866, ..., 0.00457666, 0.00228833,
        0.01372998],
       ...,
       [0.96551722, 0.08735632, 0.0754023 , ..., 0.14022988, 0.11448276,
        0.33333334],
       [0.31244123, 0.02507051, 0.02569727, ..., 0.        , 0.        ,
        0.        ],
       [0.08213166, 0.0137931 , 0.01316614, ..., 0.00564263, 0.00564263,
        0.02695925]])

In [32]:
x_train.shape

(1784, 768)

In [33]:
y_train

array([1., 1., 1., ..., 1., 1., 1.])

step2. 訓練資料

In [34]:
# sigmoid(x) function
def sigmoid(x):
  #print("show sigmoid x value: ", x)
  #print("show sigmoid value: ", 1/(1 + np.exp(-x)))
  return 1/(1 + np.exp(-x))

# activation function
def activation(x, w, b):
  #print("show np.dot: ", np.dot(x, w))
  return sigmoid(np.dot(x, w) + b)

# updata weight and bias value
def update(x, y, w, b, eta):
  y_pred = activation(x, w, b)
  #print("show y_pred: ", y_pred)
  a = (y_pred - y_train) * y_pred * (1 - y_pred)
  for i in range(pixel_num):
  #for i in range(4):
    w[i] -= eta * 1/float(len(y)) * np.sum(a * x[:, i])
  b -= eta * 1/float(len(y)) * np.sum(a)
    #print("show a*x[0:1, i]: ", a*x[0:1, i])
  return w, b

In [35]:
# initial weight value
weights = np.ones(pixel_num) / 10
bias = np.ones(1) / 10
for _ in range(1000):
  weights, bias = update(x_train, y_train, weights, bias, eta = 0.1)
  #print("weight = %f, bias = %f" % (weights, bias))
print("weights = ", weights, "bias = ", bias)

weights =  [0.01385222 0.077414   0.08230559 0.08496834 0.08503411 0.08559873
 0.08555611 0.08382456 0.08389906 0.08355603 0.08184228 0.08478284
 0.08608851 0.08709561 0.08701466 0.08720147 0.08384698 0.0867139
 0.07450014 0.08621056 0.08634304 0.08674042 0.08688284 0.08722071
 0.08687156 0.08736783 0.08226839 0.08729476 0.08734283 0.08770243
 0.08775113 0.08774295 0.08783428 0.087485   0.08771545 0.08783202
 0.0878483  0.08794578 0.08780866 0.08777384 0.0881272  0.08810057
 0.08831011 0.08828502 0.08843862 0.08852423 0.08839158 0.08852572
 0.08841018 0.08853961 0.08839673 0.08843154 0.0885599  0.08888716
 0.08895201 0.08906651 0.08910903 0.08925082 0.08924706 0.08933202
 0.08925195 0.08930732 0.08932272 0.08940417 0.08949533 0.08966509
 0.0895916  0.08963284 0.08961153 0.08970302 0.08964369 0.08979666
 0.08984076 0.08994385 0.08997305 0.09016069 0.09003061 0.09009082
 0.09048166 0.09066837 0.09068682 0.09077557 0.09069704 0.09077897
 0.09091708 0.09105236 0.09081674 0.0907639  0.09077

In [36]:
x_train

array([[0.38701805, 0.06539775, 0.08003905, ..., 0.00585652, 0.00390434,
        0.02830649],
       [0.19150989, 0.02098408, 0.01760733, ..., 0.0065123 , 0.00578871,
        0.03497347],
       [1.        , 0.12890923, 0.13424866, ..., 0.00457666, 0.00228833,
        0.01372998],
       ...,
       [0.96551722, 0.08735632, 0.0754023 , ..., 0.14022988, 0.11448276,
        0.33333334],
       [0.31244123, 0.02507051, 0.02569727, ..., 0.        , 0.        ,
        0.        ],
       [0.08213166, 0.0137931 , 0.01316614, ..., 0.00564263, 0.00564263,
        0.02695925]])

In [37]:
y_train

array([1., 1., 1., ..., 1., 1., 1.])

In [38]:
weights

array([0.01385222, 0.077414  , 0.08230559, 0.08496834, 0.08503411,
       0.08559873, 0.08555611, 0.08382456, 0.08389906, 0.08355603,
       0.08184228, 0.08478284, 0.08608851, 0.08709561, 0.08701466,
       0.08720147, 0.08384698, 0.0867139 , 0.07450014, 0.08621056,
       0.08634304, 0.08674042, 0.08688284, 0.08722071, 0.08687156,
       0.08736783, 0.08226839, 0.08729476, 0.08734283, 0.08770243,
       0.08775113, 0.08774295, 0.08783428, 0.087485  , 0.08771545,
       0.08783202, 0.0878483 , 0.08794578, 0.08780866, 0.08777384,
       0.0881272 , 0.08810057, 0.08831011, 0.08828502, 0.08843862,
       0.08852423, 0.08839158, 0.08852572, 0.08841018, 0.08853961,
       0.08839673, 0.08843154, 0.0885599 , 0.08888716, 0.08895201,
       0.08906651, 0.08910903, 0.08925082, 0.08924706, 0.08933202,
       0.08925195, 0.08930732, 0.08932272, 0.08940417, 0.08949533,
       0.08966509, 0.0895916 , 0.08963284, 0.08961153, 0.08970302,
       0.08964369, 0.08979666, 0.08984076, 0.08994385, 0.08997

In [39]:
len(weights)

768

In [40]:
for i in range(len(xfiles)):
  print(xfiles[i], y_train[i])

278_leopard.JPEG 1.0
405_leopard.JPEG 1.0
440_leopard.JPEG 1.0
539_leopard.JPEG 1.0
750_leopard.JPEG 1.0
422_leopard.JPEG 1.0
817_leopard.JPEG 1.0
696_leopard.JPEG 1.0
319_leopard.JPEG 1.0
723_leopard.JPEG 1.0
389_leopard.JPEG 1.0
210_leopard.JPEG 1.0
838_leopard.JPEG 1.0
55_leopard.JPEG 1.0
65_leopard.JPEG 1.0
738_leopard.JPEG 1.0
118_leopard.JPEG 1.0
175_leopard.JPEG 1.0
149_leopard.JPEG 1.0
561_leopard.JPEG 1.0
671_leopard.JPEG 1.0
607_leopard.JPEG 1.0
151_leopard.JPEG 1.0
376_leopard.JPEG 1.0
879_leopard.JPEG 1.0
125_leopard.JPEG 1.0
163_leopard.JPEG 1.0
271_leopard.JPEG 1.0
261_leopard.JPEG 1.0
218_leopard.JPEG 1.0
304_leopard.JPEG 1.0
348_leopard.JPEG 1.0
425_leopard.JPEG 1.0
349_leopard.JPEG 1.0
15_leopard.JPEG 1.0
522_leopard.JPEG 1.0
336_leopard.JPEG 1.0
84_leopard.JPEG 1.0
815_leopard.JPEG 1.0
834_leopard.JPEG 1.0
558_leopard.JPEG 1.0
597_leopard.JPEG 1.0
357_leopard.JPEG 1.0
135_leopard.JPEG 1.0
133_leopard.JPEG 1.0
878_leopard.JPEG 1.0
268_leopard.JPEG 1.0
29_leopard.JPEG 1

step3. 測試資料, 驗證訓練的成果

In [41]:
%cd /content/drive/MyDrive/work/NCKU/10902/dl/HW01/images/test/
test_files = os.listdir("./")
test_files_len = len(test_files)

test_sample = test_files_len
test_label  = test_files_len
# 256 * 3 = 768
pixel_num    = 768

x_test = np.empty((test_files_len, pixel_num))
y_test = np.empty(test_files_len)

print("show len test files: ", test_files_len)

test_file_idx = 0
for test_file_name in test_files:
    ext = test_file_name.split('_')
    #print("file_name and ext info: ", file_name, ext)
    if test_file_idx >= test_files_len:
      break
    if ext[-1] == "bear.JPEG":
        y_test[test_file_idx] = 0
    else:
        y_test[test_file_idx] = 1
    test_file_idx += 1

# for loop via number of pic
for dataset_num in range(test_files_len):
  print("show test pic name: ", test_files[dataset_num])
  img = cv2.imread(test_files[dataset_num])
  
  rgb_pixel = []
  # 畫出 RGB 三種顏色的分佈圖
  color = ('b','g','r')
  for i, col in enumerate(color):
    histr = cv2.calcHist([img],[i],None,[256],[0, 256])
    #plt.plot(histr, color = col)
    #plt.hist(histr.ravel(), 256, [0, 256])
    #plt.xlim([0, 256])
    
    # 顯示b, r, g的1維數值
    #print("-- ", col, " --")
    #print(histr.ravel())
    rgb_pixel.extend(histr.ravel())
  x_test[dataset_num:dataset_num + 1] = rgb_pixel[:] / max(rgb_pixel[:])
#plt.show()

/content/drive/MyDrive/work/NCKU/10902/dl/HW01/images/test
show len test files:  40
show test pic name:  4_leopard.JPEG
show test pic name:  7_leopard.JPEG
show test pic name:  16_leopard.JPEG
show test pic name:  17_leopard.JPEG
show test pic name:  3_leopard.JPEG
show test pic name:  11_leopard.JPEG
show test pic name:  0_leopard.JPEG
show test pic name:  12_leopard.JPEG
show test pic name:  19_leopard.JPEG
show test pic name:  6_leopard.JPEG
show test pic name:  18_leopard.JPEG
show test pic name:  5_leopard.JPEG
show test pic name:  13_leopard.JPEG
show test pic name:  14_leopard.JPEG
show test pic name:  10_leopard.JPEG
show test pic name:  9_leopard.JPEG
show test pic name:  1_leopard.JPEG
show test pic name:  2_leopard.JPEG
show test pic name:  15_leopard.JPEG
show test pic name:  8_leopard.JPEG
show test pic name:  7_bear.JPEG
show test pic name:  1_bear.JPEG
show test pic name:  9_bear.JPEG
show test pic name:  6_bear.JPEG
show test pic name:  2_bear.JPEG
show test pic name:  

In [42]:
activation(x_test, weights, bias)

array([0.98562348, 0.99999996, 1.        , 1.        , 0.97027987,
       0.9999999 , 0.983623  , 0.99999925, 0.84088852, 0.99999999,
       0.99999997, 0.99272632, 1.        , 0.99999899, 0.99417357,
       0.99999725, 0.9999813 , 0.99999971, 0.99999998, 0.99999992,
       1.        , 0.64670663, 1.        , 1.        , 0.99983249,
       0.97620121, 0.99999999, 0.89086675, 1.        , 1.        ,
       0.99999105, 1.        , 1.        , 1.        , 1.        ,
       0.99999865, 0.99999996, 0.99993589, 1.        , 0.99998936])

In [43]:
x_test

array([[8.12512159e-01, 2.94151932e-01, 1.02389738e-01, ...,
        5.24577405e-03, 7.18865357e-03, 3.55546921e-02],
       [2.68722475e-01, 1.82504728e-02, 2.83196978e-02, ...,
        1.88797992e-03, 6.29326620e-04, 1.00692259e-02],
       [6.39913231e-02, 6.50759228e-03, 1.51843820e-02, ...,
        4.27331895e-01, 5.91106296e-01, 9.54446852e-01],
       ...,
       [1.79354325e-02, 1.35512156e-02, 1.31526506e-02, ...,
        0.00000000e+00, 3.98565171e-04, 3.98565171e-04],
       [1.40997833e-02, 2.16919743e-03, 4.33839485e-03, ...,
        3.14533636e-02, 1.73535794e-02, 1.11713663e-01],
       [1.99106261e-01, 5.16385287e-02, 6.15690164e-02, ...,
        9.98013914e-02, 1.69811323e-01, 5.54617703e-01]])

In [44]:
x_test.max()

1.0

In [45]:
x_test.shape

(40, 768)

In [46]:
y_test

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [ ]:
for i in range(len(test_files)):
  print(test_files[i], y_test[i])

In [ ]:
weights

In [49]:
bias

array([-0.1315038])

In [50]:
print("-------------------------------------------- test -------------------------------------------------------")

-------------------------------------------- test -------------------------------------------------------
